"""
Hedgehog compatibility constants for qemu.hedgehog.

The values are chosen to match Hedgehog where possible, while exposing
QEMU backend status constants needed by the in-tree wrapper.
"""

# Copyright (C) 2026 Red Hat Inc.
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.

# Architecture constants.
HEDGEHOG_ARCH_ARM = 1
HEDGEHOG_ARCH_ARM64 = 2
HEDGEHOG_ARCH_MIPS = 3
HEDGEHOG_ARCH_X86 = 4
HEDGEHOG_ARCH_PPC = 5
HEDGEHOG_ARCH_SPARC = 6
HEDGEHOG_ARCH_M68K = 7
HEDGEHOG_ARCH_RISCV = 8
HEDGEHOG_ARCH_S390X = 9
HEDGEHOG_ARCH_TRICORE = 10
HEDGEHOG_ARCH_MAX = 11

# Mode constants.
HEDGEHOG_MODE_LITTLE_ENDIAN = 0
HEDGEHOG_MODE_BIG_ENDIAN = 1 << 30
HEDGEHOG_MODE_ARM = 0
HEDGEHOG_MODE_16 = 1 << 1
HEDGEHOG_MODE_32 = 1 << 2
HEDGEHOG_MODE_64 = 1 << 3
HEDGEHOG_MODE_THUMB = 1 << 4
HEDGEHOG_MODE_MCLASS = 1 << 5
HEDGEHOG_MODE_V8 = 1 << 6
HEDGEHOG_MODE_MICRO = 1 << 4
HEDGEHOG_MODE_MIPS3 = 1 << 5
HEDGEHOG_MODE_MIPS32R6 = 1 << 6
HEDGEHOG_MODE_MIPS32 = 1 << 2
HEDGEHOG_MODE_MIPS64 = 1 << 3
HEDGEHOG_MODE_QPX = 1 << 4
HEDGEHOG_MODE_V9 = 1 << 4
HEDGEHOG_MODE_RISCV32 = 1 << 2
HEDGEHOG_MODE_RISCV64 = 1 << 3

# Memory permissions.
HEDGEHOG_PROT_NONE = 0
HEDGEHOG_PROT_READ = 1
HEDGEHOG_PROT_WRITE = 2
HEDGEHOG_PROT_EXEC = 4
HEDGEHOG_PROT_ALL = HEDGEHOG_PROT_READ | HEDGEHOG_PROT_WRITE | HEDGEHOG_PROT_EXEC

# Hook constants.
HEDGEHOG_HOOK_INTR = 1 << 0
HEDGEHOG_HOOK_INSN = 1 << 1
HEDGEHOG_HOOK_CODE = 1 << 2
HEDGEHOG_HOOK_BLOCK = 1 << 3
HEDGEHOG_HOOK_MEM_READ_UNMAPPED = 1 << 4
HEDGEHOG_HOOK_MEM_WRITE_UNMAPPED = 1 << 5
HEDGEHOG_HOOK_MEM_FETCH_UNMAPPED = 1 << 6
HEDGEHOG_HOOK_MEM_READ_PROT = 1 << 7
HEDGEHOG_HOOK_MEM_WRITE_PROT = 1 << 8
HEDGEHOG_HOOK_MEM_FETCH_PROT = 1 << 9
HEDGEHOG_HOOK_MEM_READ = 1 << 10
HEDGEHOG_HOOK_MEM_WRITE = 1 << 11
HEDGEHOG_HOOK_MEM_FETCH = 1 << 12
HEDGEHOG_HOOK_MEM_READ_AFTER = 1 << 13
HEDGEHOG_HOOK_INSN_INVALID = 1 << 14
HEDGEHOG_HOOK_MEM_INVALID = (
    HEDGEHOG_HOOK_MEM_READ_UNMAPPED |
    HEDGEHOG_HOOK_MEM_WRITE_UNMAPPED |
    HEDGEHOG_HOOK_MEM_FETCH_UNMAPPED |
    HEDGEHOG_HOOK_MEM_READ_PROT |
    HEDGEHOG_HOOK_MEM_WRITE_PROT |
    HEDGEHOG_HOOK_MEM_FETCH_PROT
)

# Hedgehog-like error constants.
HEDGEHOG_ERR_OK = 0
HEDGEHOG_ERR_NOMEM = 1
HEDGEHOG_ERR_ARCH = 2
HEDGEHOG_ERR_HANDLE = 3
HEDGEHOG_ERR_MODE = 4
HEDGEHOG_ERR_VERSION = 5
HEDGEHOG_ERR_READ_UNMAPPED = 6
HEDGEHOG_ERR_WRITE_UNMAPPED = 7
HEDGEHOG_ERR_FETCH_UNMAPPED = 8
HEDGEHOG_ERR_HOOK = 9
HEDGEHOG_ERR_INSN_INVALID = 10
HEDGEHOG_ERR_MAP = 11
HEDGEHOG_ERR_WRITE_PROT = 12
HEDGEHOG_ERR_READ_PROT = 13
HEDGEHOG_ERR_FETCH_PROT = 14
HEDGEHOG_ERR_ARG = 15
HEDGEHOG_ERR_READ_UNALIGNED = 16
HEDGEHOG_ERR_WRITE_UNALIGNED = 17
HEDGEHOG_ERR_FETCH_UNALIGNED = 18
HEDGEHOG_ERR_HOOK_EXIST = 19
HEDGEHOG_ERR_RESOURCE = 20
HEDGEHOG_ERR_EXCEPTION = 21

# QEMU backend result constants from include/system/hedgehog-backend.h.
QEMU_HEDGEHOG_RUN_BUDGET_EXHAUSTED = 0
QEMU_HEDGEHOG_RUN_STOP_REQUESTED = 1
QEMU_HEDGEHOG_RUN_HALTED = 2
QEMU_HEDGEHOG_RUN_EXCEPTION = 3
QEMU_HEDGEHOG_RUN_INVALID_MEMORY = 4

# QEMU backend memory access constants from include/system/hedgehog-backend.h.
QEMU_HEDGEHOG_MEM_ACCESS_READ = 0
QEMU_HEDGEHOG_MEM_ACCESS_WRITE = 1
QEMU_HEDGEHOG_MEM_ACCESS_FETCH = 2

# MemTxResult constants from include/exec/memattrs.h.
QEMU_MEMTX_OK = 0
QEMU_MEMTX_ERROR = 1 << 0
QEMU_MEMTX_DECODE_ERROR = 1 << 1
QEMU_MEMTX_ACCESS_ERROR = 1 << 2

__all__ = (
    'HEDGEHOG_ARCH_ARM',
    'HEDGEHOG_ARCH_ARM64',
    'HEDGEHOG_ARCH_MIPS',
    'HEDGEHOG_ARCH_X86',
    'HEDGEHOG_ARCH_PPC',
    'HEDGEHOG_ARCH_SPARC',
    'HEDGEHOG_ARCH_M68K',
    'HEDGEHOG_ARCH_RISCV',
    'HEDGEHOG_ARCH_S390X',
    'HEDGEHOG_ARCH_TRICORE',
    'HEDGEHOG_ARCH_MAX',
    'HEDGEHOG_MODE_LITTLE_ENDIAN',
    'HEDGEHOG_MODE_BIG_ENDIAN',
    'HEDGEHOG_MODE_ARM',
    'HEDGEHOG_MODE_16',
    'HEDGEHOG_MODE_32',
    'HEDGEHOG_MODE_64',
    'HEDGEHOG_MODE_THUMB',
    'HEDGEHOG_MODE_MCLASS',
    'HEDGEHOG_MODE_V8',
    'HEDGEHOG_MODE_MICRO',
    'HEDGEHOG_MODE_MIPS3',
    'HEDGEHOG_MODE_MIPS32R6',
    'HEDGEHOG_MODE_MIPS32',
    'HEDGEHOG_MODE_MIPS64',
    'HEDGEHOG_MODE_QPX',
    'HEDGEHOG_MODE_V9',
    'HEDGEHOG_MODE_RISCV32',
    'HEDGEHOG_MODE_RISCV64',
    'HEDGEHOG_PROT_NONE',
    'HEDGEHOG_PROT_READ',
    'HEDGEHOG_PROT_WRITE',
    'HEDGEHOG_PROT_EXEC',
    'HEDGEHOG_PROT_ALL',
    'HEDGEHOG_HOOK_INTR',
    'HEDGEHOG_HOOK_INSN',
    'HEDGEHOG_HOOK_CODE',
    'HEDGEHOG_HOOK_BLOCK',
    'HEDGEHOG_HOOK_MEM_READ_UNMAPPED',
    'HEDGEHOG_HOOK_MEM_WRITE_UNMAPPED',
    'HEDGEHOG_HOOK_MEM_FETCH_UNMAPPED',
    'HEDGEHOG_HOOK_MEM_READ_PROT',
    'HEDGEHOG_HOOK_MEM_WRITE_PROT',
    'HEDGEHOG_HOOK_MEM_FETCH_PROT',
    'HEDGEHOG_HOOK_MEM_READ',
    'HEDGEHOG_HOOK_MEM_WRITE',
    'HEDGEHOG_HOOK_MEM_FETCH',
    'HEDGEHOG_HOOK_MEM_READ_AFTER',
    'HEDGEHOG_HOOK_INSN_INVALID',
    'HEDGEHOG_HOOK_MEM_INVALID',
    'HEDGEHOG_ERR_OK',
    'HEDGEHOG_ERR_NOMEM',
    'HEDGEHOG_ERR_ARCH',
    'HEDGEHOG_ERR_HANDLE',
    'HEDGEHOG_ERR_MODE',
    'HEDGEHOG_ERR_VERSION',
    'HEDGEHOG_ERR_READ_UNMAPPED',
    'HEDGEHOG_ERR_WRITE_UNMAPPED',
    'HEDGEHOG_ERR_FETCH_UNMAPPED',
    'HEDGEHOG_ERR_HOOK',
    'HEDGEHOG_ERR_INSN_INVALID',
    'HEDGEHOG_ERR_MAP',
    'HEDGEHOG_ERR_WRITE_PROT',
    'HEDGEHOG_ERR_READ_PROT',
    'HEDGEHOG_ERR_FETCH_PROT',
    'HEDGEHOG_ERR_ARG',
    'HEDGEHOG_ERR_READ_UNALIGNED',
    'HEDGEHOG_ERR_WRITE_UNALIGNED',
    'HEDGEHOG_ERR_FETCH_UNALIGNED',
    'HEDGEHOG_ERR_HOOK_EXIST',
    'HEDGEHOG_ERR_RESOURCE',
    'HEDGEHOG_ERR_EXCEPTION',
    'QEMU_HEDGEHOG_RUN_BUDGET_EXHAUSTED',
    'QEMU_HEDGEHOG_RUN_STOP_REQUESTED',
    'QEMU_HEDGEHOG_RUN_HALTED',
    'QEMU_HEDGEHOG_RUN_EXCEPTION',
    'QEMU_HEDGEHOG_RUN_INVALID_MEMORY',
    'QEMU_HEDGEHOG_MEM_ACCESS_READ',
    'QEMU_HEDGEHOG_MEM_ACCESS_WRITE',
    'QEMU_HEDGEHOG_MEM_ACCESS_FETCH',
    'QEMU_MEMTX_OK',
    'QEMU_MEMTX_ERROR',
    'QEMU_MEMTX_DECODE_ERROR',
    'QEMU_MEMTX_ACCESS_ERROR',
)
